<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Pluggin JQuery : jScrollbar</title>
	<meta http-equiv="description" content="" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="jquery/jScrollbar.jquery.css" type="text/css" />
	
	<style type="text/css">
		body {
			margin:0px;
		}
		
		.jScrollbar, 
		.jScrollbar2,
		.jScrollbar3,
		.jScrollbar4,
		.jScrollbar5
		{float:left;margin:10px}
	</style>
</head>
<body>

<!-- EXEMPLE 1 -->
<div class="jScrollbar">
	<div class="jScrollbar_mask">
		<p>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vitae nulla est. Mauris congue sem quis velit fringilla placerat mattis eros pulvinar. Curabitur lobortis lorem ut nulla ornare malesuada. Integer risus turpis, consectetur a vulputate eu, vestibulum nec dolor. Suspendisse massa magna, imperdiet ac iaculis nec, feugiat vitae justo. Sed lobortis semper eros, at bibendum orci facilisis semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae lacus massa. Etiam facilisis metus odio. Cras sit amet ipsum fermentum massa cursus elementum non vitae lectus. Maecenas porta, felis eu volutpat luctus, nunc massa ullamcorper leo, sed sollicitudin odio justo eu ante. Etiam pharetra pharetra rhoncus. Praesent pretium ornare consectetur. Proin lacinia pellentesque mattis. Vestibulum egestas, leo quis cursus pellentesque, metus enim interdum justo, vitae rhoncus dui nisi eu dui.
			Proin venenatis, purus quis posuere adipiscing, felis turpis fermentum leo, sed pharetra tortor magna mattis enim. Vivamus urna lacus, blandit non aliquam vel, condimentum in magna. Maecenas suscipit sagittis nibh, a ultrices dui blandit eu. Aliquam urna erat, hendrerit sed gravida vitae, sodales sit amet ligula. Maecenas lobortis dolor eu sem porta pretium. Duis eu consectetur magna. Nullam egestas nunc sed lorem gravida eu congue nisl commodo. Etiam id enim urna. Ut consequat ultricies diam in dignissim. Morbi mi quam, aliquet posuere feugiat vitae, ornare vel lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis in dignissim orci. Phasellus viverra ullamcorper mollis. Sed aliquam commodo posuere. Cras non varius libero. Nulla consequat mi elementum libero porttitor tincidunt. Mauris venenatis malesuada sagittis. Nam viverra risus ut tortor convallis porttitor. Morbi convallis commodo massa, quis viverra massa pretium vitae. 
		</p>
	</div>
	
	<div class="jScrollbar_draggable">
		<a href="#" class="draggable"></a>
	</div>
		
	<div class="clr"></div>
</div>

<div style="margin-top:30px;"></div>

<!-- EXEMPLE 2 -->
<div class="jScrollbar2">
	<div class="jScrollbar_mask">
		<p>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vitae nulla est. Mauris congue sem quis velit fringilla placerat mattis eros pulvinar. Curabitur lobortis lorem ut nulla ornare malesuada. Integer risus turpis, consectetur a vulputate eu, vestibulum nec dolor. Suspendisse massa magna, imperdiet ac iaculis nec, feugiat vitae justo. Sed lobortis semper eros, at bibendum orci facilisis semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae lacus massa. Etiam facilisis metus odio. Cras sit amet ipsum fermentum massa cursus elementum non vitae lectus. Maecenas porta, felis eu volutpat luctus, nunc massa ullamcorper leo, sed sollicitudin odio justo eu ante. Etiam pharetra pharetra rhoncus. Praesent pretium ornare consectetur. Proin lacinia pellentesque mattis. Vestibulum egestas, leo quis cursus pellentesque, metus enim interdum justo, vitae rhoncus dui nisi eu dui.
			Proin venenatis, purus quis posuere adipiscing, felis turpis fermentum leo, sed pharetra tortor magna mattis enim. Vivamus urna lacus, blandit non aliquam vel, condimentum in magna. Maecenas suscipit sagittis nibh, a ultrices dui blandit eu. Aliquam urna erat, hendrerit sed gravida vitae, sodales sit amet ligula. Maecenas lobortis dolor eu sem porta pretium. Duis eu consectetur magna. Nullam egestas nunc sed lorem gravida eu congue nisl commodo. Etiam id enim urna. Ut consequat ultricies diam in dignissim. Morbi mi quam, aliquet posuere feugiat vitae, ornare vel lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis in dignissim orci. Phasellus viverra ullamcorper mollis. Sed aliquam commodo posuere. Cras non varius libero. Nulla consequat mi elementum libero porttitor tincidunt. Mauris venenatis malesuada sagittis. Nam viverra risus ut tortor convallis porttitor. Morbi convallis commodo massa, quis viverra massa pretium vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vitae nulla est. Mauris congue sem quis velit fringilla placerat mattis eros pulvinar. Curabitur lobortis lorem ut nulla ornare malesuada. Integer risus turpis, consectetur a vulputate eu, vestibulum nec dolor. Suspendisse massa magna, imperdiet ac iaculis nec, feugiat vitae justo. Sed lobortis semper eros, at bibendum orci facilisis semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae lacus massa. Etiam facilisis metus odio. Cras sit amet ipsum fermentum massa cursus elementum non vitae lectus. Maecenas porta, felis eu volutpat luctus, nunc massa ullamcorper leo, sed sollicitudin odio justo eu ante. Etiam pharetra pharetra rhoncus. Praesent pretium ornare consectetur. Proin lacinia pellentesque mattis. Vestibulum egestas, leo quis cursus pellentesque, metus enim interdum justo, vitae rhoncus dui nisi eu dui.
			Proin venenatis, purus quis posuere adipiscing, felis turpis fermentum leo, sed pharetra tortor magna mattis enim. Vivamus urna lacus, blandit non aliquam vel, condimentum in magna. Maecenas suscipit sagittis nibh, a ultrices dui blandit eu. Aliquam urna erat, hendrerit sed gravida vitae, sodales sit amet ligula. Maecenas lobortis dolor eu sem porta pretium. Duis eu consectetur magna. Nullam egestas nunc sed lorem gravida eu congue nisl commodo. Etiam id enim urna. Ut consequat ultricies diam in dignissim. Morbi mi quam, aliquet posuere feugiat vitae, ornare vel lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis in dignissim orci. Phasellus viverra ullamcorper mollis. Sed aliquam commodo posuere. Cras non varius libero. Nulla consequat mi elementum libero porttitor tincidunt. Mauris venenatis malesuada sagittis. Nam viverra risus ut tortor convallis porttitor. Morbi convallis commodo massa, quis viverra massa pretium vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vitae nulla est. Mauris congue sem quis velit fringilla placerat mattis eros pulvinar. Curabitur lobortis lorem ut nulla ornare malesuada. Integer risus turpis, consectetur a vulputate eu, vestibulum nec dolor. Suspendisse massa magna, imperdiet ac iaculis nec, feugiat vitae justo. Sed lobortis semper eros, at bibendum orci facilisis semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae lacus massa. Etiam facilisis metus odio. Cras sit amet ipsum fermentum massa cursus elementum non vitae lectus. Maecenas porta, felis eu volutpat luctus, nunc massa ullamcorper leo, sed sollicitudin odio justo eu ante. Etiam pharetra pharetra rhoncus. Praesent pretium ornare consectetur. Proin lacinia pellentesque mattis. Vestibulum egestas, leo quis cursus pellentesque, metus enim interdum justo, vitae rhoncus dui nisi eu dui.
			Proin venenatis, purus quis posuere adipiscing, felis turpis fermentum leo, sed pharetra tortor magna mattis enim. Vivamus urna lacus, blandit non aliquam vel, condimentum in magna. Maecenas suscipit sagittis nibh, a ultrices dui blandit eu. Aliquam urna erat, hendrerit sed gravida vitae, sodales sit amet ligula. Maecenas lobortis dolor eu sem porta pretium. Duis eu consectetur magna. Nullam egestas nunc sed lorem gravida eu congue nisl commodo. Etiam id enim urna. Ut consequat ultricies diam in dignissim. Morbi mi quam, aliquet posuere feugiat vitae, ornare vel lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis in dignissim orci. Phasellus viverra ullamcorper mollis. Sed aliquam commodo posuere. Cras non varius libero. Nulla consequat mi elementum libero porttitor tincidunt. Mauris venenatis malesuada sagittis. Nam viverra risus ut tortor convallis porttitor. Morbi convallis commodo massa, quis viverra massa pretium vitae. 
		</p>
	</div>
	
	<div class="jScrollbar_draggable">
		<a href="#" class="draggable"></a>
	</div>
		
	<div class="clr"></div>
</div>

<div style="margin-top:30px;clear:both"></div>

<!-- EXEMPLE 3 -->
<div class="jScrollbar3">
	<div class="jScrollbar_mask">
		<p>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vitae nulla est. Mauris congue sem quis velit fringilla placerat mattis eros pulvinar. Curabitur lobortis lorem ut nulla ornare malesuada. Integer risus turpis, consectetur a vulputate eu, vestibulum nec dolor. Suspendisse massa magna, imperdiet ac iaculis nec, feugiat vitae justo. Sed lobortis semper eros, at bibendum orci facilisis semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae lacus massa. Etiam facilisis metus odio. Cras sit amet ipsum fermentum massa cursus elementum non vitae lectus. Maecenas porta, felis eu volutpat luctus, nunc massa ullamcorper leo, sed sollicitudin odio justo eu ante. Etiam pharetra pharetra rhoncus. Praesent pretium ornare consectetur. Proin lacinia pellentesque mattis. Vestibulum egestas, leo quis cursus pellentesque, metus enim interdum justo, vitae rhoncus dui nisi eu dui.
			Proin venenatis, purus quis posuere adipiscing, felis turpis fermentum leo, sed pharetra tortor magna mattis enim. Vivamus urna lacus, blandit non aliquam vel, condimentum in magna. Maecenas suscipit sagittis nibh, a ultrices dui blandit eu. Aliquam urna erat, hendrerit sed gravida vitae, sodales sit amet ligula. Maecenas lobortis dolor eu sem porta pretium. Duis eu consectetur magna. Nullam egestas nunc sed lorem gravida eu congue nisl commodo. Etiam id enim urna. Ut consequat ultricies diam in dignissim. Morbi mi quam, aliquet posuere feugiat vitae, ornare vel lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis in dignissim orci. Phasellus viverra ullamcorper mollis. Sed aliquam commodo posuere. Cras non varius libero. Nulla consequat mi elementum libero porttitor tincidunt. Mauris venenatis malesuada sagittis. Nam viverra risus ut tortor convallis porttitor. Morbi convallis commodo massa, quis viverra massa pretium vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vitae nulla est. Mauris congue sem quis velit fringilla placerat mattis eros pulvinar. Curabitur lobortis lorem ut nulla ornare malesuada. Integer risus turpis, consectetur a vulputate eu, vestibulum nec dolor. Suspendisse massa magna, imperdiet ac iaculis nec, feugiat vitae justo. Sed lobortis semper eros, at bibendum orci facilisis semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae lacus massa. Etiam facilisis metus odio. Cras sit amet ipsum fermentum massa cursus elementum non vitae lectus. Maecenas porta, felis eu volutpat luctus, nunc massa ullamcorper leo, sed sollicitudin odio justo eu ante. Etiam pharetra pharetra rhoncus. Praesent pretium ornare consectetur. Proin lacinia pellentesque mattis. Vestibulum egestas, leo quis cursus pellentesque, metus enim interdum justo, vitae rhoncus dui nisi eu dui.
			Proin venenatis, purus quis posuere adipiscing, felis turpis fermentum leo, sed pharetra tortor magna mattis enim. Vivamus urna lacus, blandit non aliquam vel, condimentum in magna. Maecenas suscipit sagittis nibh, a ultrices dui blandit eu. Aliquam urna erat, hendrerit sed gravida vitae, sodales sit amet ligula. Maecenas lobortis dolor eu sem porta pretium. Duis eu consectetur magna. Nullam egestas nunc sed lorem gravida eu congue nisl commodo. Etiam id enim urna. Ut consequat ultricies diam in dignissim. Morbi mi quam, aliquet posuere feugiat vitae, ornare vel lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis in dignissim orci. Phasellus viverra ullamcorper mollis. Sed aliquam commodo posuere. Cras non varius libero. Nulla consequat mi elementum libero porttitor tincidunt. Mauris venenatis malesuada sagittis. Nam viverra risus ut tortor convallis porttitor. Morbi convallis commodo massa, quis viverra massa pretium vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vitae nulla est. Mauris congue sem quis velit fringilla placerat mattis eros pulvinar. Curabitur lobortis lorem ut nulla ornare malesuada. Integer risus turpis, consectetur a vulputate eu, vestibulum nec dolor. Suspendisse massa magna, imperdiet ac iaculis nec, feugiat vitae justo. Sed lobortis semper eros, at bibendum orci facilisis semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae lacus massa. Etiam facilisis metus odio. Cras sit amet ipsum fermentum massa cursus elementum non vitae lectus. Maecenas porta, felis eu volutpat luctus, nunc massa ullamcorper leo, sed sollicitudin odio justo eu ante. Etiam pharetra pharetra rhoncus. Praesent pretium ornare consectetur. Proin lacinia pellentesque mattis. Vestibulum egestas, leo quis cursus pellentesque, metus enim interdum justo, vitae rhoncus dui nisi eu dui.
			Proin venenatis, purus quis posuere adipiscing, felis turpis fermentum leo, sed pharetra tortor magna mattis enim. Vivamus urna lacus, blandit non aliquam vel, condimentum in magna. Maecenas suscipit sagittis nibh, a ultrices dui blandit eu. Aliquam urna erat, hendrerit sed gravida vitae, sodales sit amet ligula. Maecenas lobortis dolor eu sem porta pretium. Duis eu consectetur magna. Nullam egestas nunc sed lorem gravida eu congue nisl commodo. Etiam id enim urna. Ut consequat ultricies diam in dignissim. Morbi mi quam, aliquet posuere feugiat vitae, ornare vel lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis in dignissim orci. Phasellus viverra ullamcorper mollis. Sed aliquam commodo posuere. Cras non varius libero. Nulla consequat mi elementum libero porttitor tincidunt. Mauris venenatis malesuada sagittis. Nam viverra risus ut tortor convallis porttitor. Morbi convallis commodo massa, quis viverra massa pretium vitae. 
		</p>
	</div>
	
	<div class="jScrollbar_draggable">
		<a href="#" class="draggable"></a>
	</div>
		
	<div class="clr"></div>
</div>

<div style="margin-top:30px;"></div>

<!-- EXEMPLE 4 -->
<div class="jScrollbar4">
	<div class="jScrollbar_mask">
		<p>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vitae nulla est. Mauris congue sem quis velit fringilla placerat mattis eros pulvinar. Curabitur lobortis lorem ut nulla ornare malesuada. Integer risus turpis, consectetur a vulputate eu, vestibulum nec dolor. Suspendisse massa magna, imperdiet ac iaculis nec, feugiat vitae justo. Sed lobortis semper eros, at bibendum orci facilisis semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae lacus massa. Etiam facilisis metus odio. Cras sit amet ipsum fermentum massa cursus elementum non vitae lectus. Maecenas porta, felis eu volutpat luctus, nunc massa ullamcorper leo, sed sollicitudin odio justo eu ante. Etiam pharetra pharetra rhoncus. Praesent pretium ornare consectetur. Proin lacinia pellentesque mattis. Vestibulum egestas, leo quis cursus pellentesque, metus enim interdum justo, vitae rhoncus dui nisi eu dui.
			Proin venenatis, purus quis posuere adipiscing, felis turpis fermentum leo, sed pharetra tortor magna mattis enim. Vivamus urna lacus, blandit non aliquam vel, condimentum in magna. Maecenas suscipit sagittis nibh, a ultrices dui blandit eu. Aliquam urna erat, hendrerit sed gravida vitae, sodales sit amet ligula. Maecenas lobortis dolor eu sem porta pretium. Duis eu consectetur magna. Nullam egestas nunc sed lorem gravida eu congue nisl commodo. Etiam id enim urna. Ut consequat ultricies diam in dignissim. Morbi mi quam, aliquet posuere feugiat vitae, ornare vel lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis in dignissim orci. Phasellus viverra ullamcorper mollis. Sed aliquam commodo posuere. Cras non varius libero. Nulla consequat mi elementum libero porttitor tincidunt. Mauris venenatis malesuada sagittis. Nam viverra risus ut tortor convallis porttitor. Morbi convallis commodo massa, quis viverra massa pretium vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vitae nulla est. Mauris congue sem quis velit fringilla placerat mattis eros pulvinar. Curabitur lobortis lorem ut nulla ornare malesuada. Integer risus turpis, consectetur a vulputate eu, vestibulum nec dolor. Suspendisse massa magna, imperdiet ac iaculis nec, feugiat vitae justo. Sed lobortis semper eros, at bibendum orci facilisis semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae lacus massa. Etiam facilisis metus odio. Cras sit amet ipsum fermentum massa cursus elementum non vitae lectus. Maecenas porta, felis eu volutpat luctus, nunc massa ullamcorper leo, sed sollicitudin odio justo eu ante. Etiam pharetra pharetra rhoncus. Praesent pretium ornare consectetur. Proin lacinia pellentesque mattis. Vestibulum egestas, leo quis cursus pellentesque, metus enim interdum justo, vitae rhoncus dui nisi eu dui.
			Proin venenatis, purus quis posuere adipiscing, felis turpis fermentum leo, sed pharetra tortor magna mattis enim. Vivamus urna lacus, blandit non aliquam vel, condimentum in magna. Maecenas suscipit sagittis nibh, a ultrices dui blandit eu. Aliquam urna erat, hendrerit sed gravida vitae, sodales sit amet ligula. Maecenas lobortis dolor eu sem porta pretium. Duis eu consectetur magna. Nullam egestas nunc sed lorem gravida eu congue nisl commodo. Etiam id enim urna. Ut consequat ultricies diam in dignissim. Morbi mi quam, aliquet posuere feugiat vitae, ornare vel lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis in dignissim orci. Phasellus viverra ullamcorper mollis. Sed aliquam commodo posuere. Cras non varius libero. Nulla consequat mi elementum libero porttitor tincidunt. Mauris venenatis malesuada sagittis. Nam viverra risus ut tortor convallis porttitor. Morbi convallis commodo massa, quis viverra massa pretium vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vitae nulla est. Mauris congue sem quis velit fringilla placerat mattis eros pulvinar. Curabitur lobortis lorem ut nulla ornare malesuada. Integer risus turpis, consectetur a vulputate eu, vestibulum nec dolor. Suspendisse massa magna, imperdiet ac iaculis nec, feugiat vitae justo. Sed lobortis semper eros, at bibendum orci facilisis semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae lacus massa. Etiam facilisis metus odio. Cras sit amet ipsum fermentum massa cursus elementum non vitae lectus. Maecenas porta, felis eu volutpat luctus, nunc massa ullamcorper leo, sed sollicitudin odio justo eu ante. Etiam pharetra pharetra rhoncus. Praesent pretium ornare consectetur. Proin lacinia pellentesque mattis. Vestibulum egestas, leo quis cursus pellentesque, metus enim interdum justo, vitae rhoncus dui nisi eu dui.
			Proin venenatis, purus quis posuere adipiscing, felis turpis fermentum leo, sed pharetra tortor magna mattis enim. Vivamus urna lacus, blandit non aliquam vel, condimentum in magna. Maecenas suscipit sagittis nibh, a ultrices dui blandit eu. Aliquam urna erat, hendrerit sed gravida vitae, sodales sit amet ligula. Maecenas lobortis dolor eu sem porta pretium. Duis eu consectetur magna. Nullam egestas nunc sed lorem gravida eu congue nisl commodo. Etiam id enim urna. Ut consequat ultricies diam in dignissim. Morbi mi quam, aliquet posuere feugiat vitae, ornare vel lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis in dignissim orci. Phasellus viverra ullamcorper mollis. Sed aliquam commodo posuere. Cras non varius libero. Nulla consequat mi elementum libero porttitor tincidunt. Mauris venenatis malesuada sagittis. Nam viverra risus ut tortor convallis porttitor. Morbi convallis commodo massa, quis viverra massa pretium vitae. 
		</p>
	</div>
	
	<div class="jScrollbar_draggable">
		<a href="#" class="draggable"></a>
	</div>
		
	<div class="clr"></div>
</div>

<div style="margin-top:30px;clear:both"></div>

<!-- EXEMPLE 5 -->
<div class="jScrollbar5">
	<div class="jScrollbar_mask">
		<p>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vitae nulla est. Mauris congue sem quis velit fringilla placerat mattis eros pulvinar. Curabitur lobortis lorem ut nulla ornare malesuada. Integer risus turpis, consectetur a vulputate eu, vestibulum nec dolor. Suspendisse massa magna, imperdiet ac iaculis nec, feugiat vitae justo. Sed lobortis semper eros, at bibendum orci facilisis semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae lacus massa. Etiam facilisis metus odio. Cras sit amet ipsum fermentum massa cursus elementum non vitae lectus. Maecenas porta, felis eu volutpat luctus, nunc massa ullamcorper leo, sed sollicitudin odio justo eu ante. Etiam pharetra pharetra rhoncus. Praesent pretium ornare consectetur. Proin lacinia pellentesque mattis. Vestibulum egestas, leo quis cursus pellentesque, metus enim interdum justo, vitae rhoncus dui nisi eu dui.
			Proin venenatis, purus quis posuere adipiscing, felis turpis fermentum leo, sed pharetra tortor magna mattis enim. Vivamus urna lacus, blandit non aliquam vel, condimentum in magna. Maecenas suscipit sagittis nibh, a ultrices dui blandit eu. Aliquam urna erat, hendrerit sed gravida vitae, sodales sit amet ligula. Maecenas lobortis dolor eu sem porta pretium. Duis eu consectetur magna. Nullam egestas nunc sed lorem gravida eu congue nisl commodo. Etiam id enim urna. Ut consequat ultricies diam in dignissim. Morbi mi quam, aliquet posuere feugiat vitae, ornare vel lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis in dignissim orci. Phasellus viverra ullamcorper mollis. Sed aliquam commodo posuere. Cras non varius libero. Nulla consequat mi elementum libero porttitor tincidunt. Mauris venenatis malesuada sagittis. Nam viverra risus ut tortor convallis porttitor. Morbi convallis commodo massa, quis viverra massa pretium vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vitae nulla est. Mauris congue sem quis velit fringilla placerat mattis eros pulvinar. Curabitur lobortis lorem ut nulla ornare malesuada. Integer risus turpis, consectetur a vulputate eu, vestibulum nec dolor. Suspendisse massa magna, imperdiet ac iaculis nec, feugiat vitae justo. Sed lobortis semper eros, at bibendum orci facilisis semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae lacus massa. Etiam facilisis metus odio. Cras sit amet ipsum fermentum massa cursus elementum non vitae lectus. Maecenas porta, felis eu volutpat luctus, nunc massa ullamcorper leo, sed sollicitudin odio justo eu ante. Etiam pharetra pharetra rhoncus. Praesent pretium ornare consectetur. Proin lacinia pellentesque mattis. Vestibulum egestas, leo quis cursus pellentesque, metus enim interdum justo, vitae rhoncus dui nisi eu dui.
			Proin venenatis, purus quis posuere adipiscing, felis turpis fermentum leo, sed pharetra tortor magna mattis enim. Vivamus urna lacus, blandit non aliquam vel, condimentum in magna. Maecenas suscipit sagittis nibh, a ultrices dui blandit eu. Aliquam urna erat, hendrerit sed gravida vitae, sodales sit amet ligula. Maecenas lobortis dolor eu sem porta pretium. Duis eu consectetur magna. Nullam egestas nunc sed lorem gravida eu congue nisl commodo. Etiam id enim urna. Ut consequat ultricies diam in dignissim. Morbi mi quam, aliquet posuere feugiat vitae, ornare vel lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis in dignissim orci. Phasellus viverra ullamcorper mollis. Sed aliquam commodo posuere. Cras non varius libero. Nulla consequat mi elementum libero porttitor tincidunt. Mauris venenatis malesuada sagittis. Nam viverra risus ut tortor convallis porttitor. Morbi convallis commodo massa, quis viverra massa pretium vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vitae nulla est. Mauris congue sem quis velit fringilla placerat mattis eros pulvinar. Curabitur lobortis lorem ut nulla ornare malesuada. Integer risus turpis, consectetur a vulputate eu, vestibulum nec dolor. Suspendisse massa magna, imperdiet ac iaculis nec, feugiat vitae justo. Sed lobortis semper eros, at bibendum orci facilisis semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae lacus massa. Etiam facilisis metus odio. Cras sit amet ipsum fermentum massa cursus elementum non vitae lectus. Maecenas porta, felis eu volutpat luctus, nunc massa ullamcorper leo, sed sollicitudin odio justo eu ante. Etiam pharetra pharetra rhoncus. Praesent pretium ornare consectetur. Proin lacinia pellentesque mattis. Vestibulum egestas, leo quis cursus pellentesque, metus enim interdum justo, vitae rhoncus dui nisi eu dui.
			Proin venenatis, purus quis posuere adipiscing, felis turpis fermentum leo, sed pharetra tortor magna mattis enim. Vivamus urna lacus, blandit non aliquam vel, condimentum in magna. Maecenas suscipit sagittis nibh, a ultrices dui blandit eu. Aliquam urna erat, hendrerit sed gravida vitae, sodales sit amet ligula. Maecenas lobortis dolor eu sem porta pretium. Duis eu consectetur magna. Nullam egestas nunc sed lorem gravida eu congue nisl commodo. Etiam id enim urna. Ut consequat ultricies diam in dignissim. Morbi mi quam, aliquet posuere feugiat vitae, ornare vel lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis in dignissim orci. Phasellus viverra ullamcorper mollis. Sed aliquam commodo posuere. Cras non varius libero. Nulla consequat mi elementum libero porttitor tincidunt. Mauris venenatis malesuada sagittis. Nam viverra risus ut tortor convallis porttitor. Morbi convallis commodo massa, quis viverra massa pretium vitae. 
		</p>
	</div>
	
	<div class="jScrollbar_draggable">
		<a href="#" class="draggable"></a>
	</div>
		
	<div class="clr"></div>
</div>
<script type="text/javascript" src="jquery/jquery.js"></script>           
<script type="text/javascript" src="jquery/jquery-ui.js"></script>        
<script type="text/javascript" src="jquery/jquery-mousewheel.js"></script>
<script type="text/javascript" src="jquery/jScrollbar.jquery.js"></script>
<script type="text/javascript">                                           
	$(document).ready(function(){
		$('.jScrollbar, .jScrollbar2, .jScrollbar3, .jScrollbar4, .jScrollbar5').jScrollbar();
	});                                        
</script>                                                                 
</body>                                                                   
</html>